
services:
  app:
    build: .
    # Mapping the container's port to my machine's port
    ports:
      - "5173:5173"
    # CRITICAL: Mount the source code using a volume
    volumes:
      - .:/app
      # ðŸš¨ CRITICAL: Tell Docker to ignore the local node_modules
      - /app/node_modules
    environment:
      # sometimes help with hot-reloading issues in WSL2
      CHOKIDAR_USEPOLLING: "true"